version: '3'

######### Services ###################################

services:
  # Server container
  nginx:
    image: trust-review_nginx:development
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./docker/nginx/logs:/var/log/nginx
    ports:
      # Nuxt port
      - 8080:80
      # Laravel port
      - 8081:81
    links:
      - client
      - php

  # PHP FastCGI Process Manager container
  php:
    image: trust-review_php:development
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www/api
    environment:
      # If you down want to use xDebug, set remote_enable=0
      XDEBUG_CONFIG: "remote_enable=0 idekey=PHPSTORM"
      PHP_IDE_CONFIG: "serverName=Docker"
    links:
      - postgres

  # PostgreSQL database container
  postgres:
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    volumes:
      # Database volume
      - database:/var/lib/postgresql/data
      # Temp volume to allow using dumps
      - ./docker/postgres/dumps/:/tmp/
    ports:
      - 54321:5432
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app

  adminer:
    image: adnan007/adminer
    restart: always
    ports:
      - 8082:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DEFAULT_DRIVER=pgsql
      - ADMINER_DEFAULT_USERNAME=app
      - ADMINER_DEFAULT_PASSWORD=app
      - ADMINER_DEFAULT_DB=app

  # Mailhog container (SMTP testing)
  mailhog:
    build:
      context: docker/mailhog
      dockerfile: Dockerfile
    ports:
      - 8026:8025

  # Client container
  client:
    image: trust-review_client:development
    build:
      context: docker/client
      dockerfile: Dockerfile
    volumes:
      - ./client:/var/www/client
      
######### Volumes ###################################

volumes:
  database:
    driver: local